# fly.toml app configuration file generated for gp-tracker-hidden-rain-8594 on 2025-12-12T09:16:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gp-tracker-hidden-rain-8594'
primary_region = 'jnb'

[build]

[deploy]
  release_command = "cp /app/gp_tracker.db /data/gp_tracker.db"

[env]
  DB_PATH = '/data/gp_tracker.db'
  PORT = '8080'

[[mounts]]
  source = 'gp_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
